- stat: path="{{ elk_base_path }}"
  register: elk_base_path_check

- name:  create base dir for ELK
  file:
    path: "{{ elk_base_path }}"
    state: directory
    owner: "{{ elk_user }}"
    group: "{{ elk_group }}"
    mode: 0770
  # when: not elk_base_path_check.stat.exists
